name: Publish npm package

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Verify version change
        id: check_version
        run: |
          OLD_VERSION=$(git show HEAD~1:package.json | jq -r '.version')
          NEW_VERSION=$(jq -r '.version' package.json)
          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "::set-output name=changed::false"
            echo "Version has not changed."
          else
            echo "::set-output name=changed::true"
            echo "Version has changed from $OLD_VERSION to $NEW_VERSION."
          fi

      - name: Parepare package
        if: steps.check_version.outputs.changed == 'true'
        run: |
          npm install
          npm run build

      - name: Publish to npm
        if: steps.check_version.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Push tags
        if: steps.check_version.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$(jq -r '.version' package.json)"
          git push origin --tags
